version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
    depends_on:
      - postgres

  marquez-web:
    image: marquezproject/marquez-web:latest
    ports:
      - "3000:3000"
    environment:
      - WEB_PORT=3000
      - MARQUEZ_URL=http://localhost:5000
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    depends_on:
      - marquez

volumes:
  postgres_data:
